name: build and test

on:
  push:
    branches: [ main, fix-ci ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-12
    env:
      device: iPhone 12 Pro
      scheme: ViewSnapshots
      project: ViewSnapshots.xcodeproj
      destination: "platform=iOS Simulator,name=iPhone 12 Pro"

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - name: Install Node dependencies
        run: yarn install --frozen-lockfile
      - name: Visual regression testing
        uses: bokuweb/reg-actions@v1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          image-directory-path: AppTests/Snapshots
          enable-antialias: true
          matching-threshold: 0.02
          threshold-rate: 0.001
      - name: Show Hardware Info
        run: ./ci_scripts/ci_post_clone.sh
      - name: Resolve dependencies
        run: >
          xcodebuild -resolvePackageDependencies
          -project $project
          -scheme $scheme
          -destination "$destination"
      - name: Build
        uses: sersoft-gmbh/xcodebuild-action@master
        with:
          action: build-for-testing
          project: ${{ env.project }}
          scheme: ${{ env.scheme }}
          destination: ${{ env.destination }}
      - name: Test
        uses: sersoft-gmbh/xcodebuild-action@master
        with:
          action: test-without-building
          result-bundle-path: test-results/all-tests
          project: ${{ env.project }}
          scheme: ${{ env.scheme }}
          destination: ${{ env.destination }}
      - name: Archive results # due to: https://github.com/actions/upload-artifact/issues/243
        if: always()
        run: zip -FSry results.zip test-results || true
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: results.zip
